module.exports = {
  convertTable: [
 ["Ain", "AIN" ],
 ["Aisne",  "AISNE" ],
 ["Allier",  "ALLIER" ],
 ["Alpes-Maritimes",  "ALPES-MARITIMES" ],
 ["Alpes-de-Haute-Provence",  "ALPES DE HAUTE PROVENCE" ],
 ["Ardennes",  "ARDENNES" ],
 ["Ardèche",  "ARDECHE" ],
 ["Ariège",  "ARIEGE" ],
 ["Aube",  "AUBE" ],
 ["Aude",  "AUDE" ],
 ["Aveyron",  "AVEYRON" ],
 ["Bas-Rhin",  "BAS-RHIN" ],
 ["Bouches-du-Rhône",  "BOUCHES DU RHONE" ],
 ["Calvados",  "CALVADOS" ],
 ["Cantal",  "CANTAL" ],
 ["Charente",  "CHARENTE" ],
 ["Charente-Maritime",  "CHARENTE-MARITIME" ],
 ["Cher",  "CHER" ],
 ["Corrèze",  "CORREZE" ],
 ["Corse-du-Sud",  "CORSE DU SUD" ],
 ["Creuse",  "CREUSE" ],
 ["Côte-d'Or",  "CÔTE D’OR" ],
 ["Côtes-d'Armor",  "COTES D'ARMOR" ],
 ["Deux-Sèvres",  "DEUX-SEVRES" ],
 ["Dordogne",  "DORDOGNE" ],
 ["Doubs",  "DOUBS" ],
 ["Drôme",  "DRÔME" ],
 ["Essonne",  "ESSONNE" ],
 ["Eure",  "EURE" ],
 ["Eure-et-Loir",  "EURE ET LOIR" ],
 ["Finistère",  "FINISTERE" ],
 ["Gard",  "GARD" ],
 ["Gers",  "GERS" ],
 ["Gironde",  "GIRONDE" ],
 ["Haut-Rhin",  "HAUT-RHIN" ],
 ["Haute-Corse",  "HAUTE-CORSE" ],
 ["Haute-Garonne",  "HAUTE-GARONNE" ],
 ["Haute-Loire",  "HAUTE-LOIRE" ],
 ["Haute-Marne",  "HAUTE-MARNE" ],
 ["Haute-Savoie",  "HAUTE-SAVOIE" ],
 ["Haute-Saône",  "HAUTE-SAONE" ],
 ["Haute-Vienne",  "HAUTE VIENNE" ],
 ["Hautes-Alpes",  "HAUTES-ALPES" ],
 ["Hautes-Pyrénées",  "HAUTES-PYRENEES" ],
 ["Hauts-de-Seine",  "HAUTS DE SEINE" ],
 ["Hérault",  "HERAULT" ],
 ["Ille-et-Vilaine",  "ILE ET VILAINE" ],
 ["Indre",  "INDRE" ],
 ["Indre-et-Loire",  "INDRE ET LOIRE" ],
 ["Isère",  "ISERE" ],
 ["Jura",  "JURA" ],
 ["Landes",  "LANDES" ],
 ["Loir-et-Cher",  "LOIR ET CHER" ],
 ["Loire",  "LOIRE" ],
 ["Loire-Atlantique",  "LOIRE-ATLANTIQUE" ],
 ["Loiret",  "LOIRET" ],
 ["Lot",  "LOT" ],
 ["Lot-et-Garonne",  "LOT ET GARONNE" ],
 ["Lozère",  "LOZERE" ],
 ["Maine-et-Loire",  "MAINE-ET-LOIRE" ],
 ["Manche",  "MANCHE" ],
 ["Marne",  "MARNE" ],
 ["Mayenne",  "MAYENNE" ],
 ["Meurthe-et-Moselle",  "MEURTHE ET MOSELLE" ],
 ["Meuse",  "MEUSE" ],
 ["Morbihan",  "MORBIHAN" ],
 ["Moselle",  "MOSELLE" ],
 ["Nièvre",  "NIÈVRE" ],
 ["Nord",  "NORD" ],
 ["Oise",  "OISE" ],
 ["Orne",  "ORNE" ],
 ["Paris",  "PARIS" ],
 ["Pas-de-Calais",  "PAS-DE-CALAIS" ],
 ["Puy-de-Dôme",  "PUY DE DÔME" ],
 ["Pyrénées-Atlantiques",  "PYRÉNÉES ATLANTIQUES" ],
 ["Pyrénées-Orientales",  "PYRENEES ORIENTALES" ],
 ["Rhône",  "RHÔNE" ],
 ["Sarthe",  "SARTHE" ],
 ["Savoie",  "SAVOIE" ],
 ["Saône-et-Loire",  "SAONE ET LOIRE" ],
 ["Seine-Maritime",  "SEINE-MARITIME" ],
 ["Seine-Saint-Denis",  "SEINE SAINT-DENIS" ],
 ["Seine-et-Marne",  "SEINE ET MARNE" ],
 ["Somme",  "SOMME" ],
 ["Tarn",  "TARN" ],
 ["Tarn-et-Garonne",  "TARN-ET-GARONNE" ],
 ["Territoire de Belfort",  "TERRITOIRE DE BELFORT" ],
 ["Val-d'Oise",  "VAL D'OISE" ],
 ["Val-de-Marne",  "VAL DE MARNE" ],
 ["Var",  "VAR" ],
 ["Vaucluse",  "VAUCLUSE" ],
 ["Vendée",  "VENDEE" ],
 ["Vienne",  "VIENNE" ],
 ["Vosges",  "VOSGES" ],
 ["Yonne",  "YONNE" ],
 ["Yvelines", "YVELINES" ]
]
}
